import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorial: [
    {
      type: 'autogenerated',
      dirName: 'tutorial'
    }
  ],
  features: [
    {
      type: 'autogenerated',
      dirName: 'features'
    }
  ],
  restApi: [
    {
      type: 'autogenerated',
      dirName: 'api/rest'
    },
    {
      type: 'category',
      label: 'User API',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/user',
        }
      ],
    },
    {
      type: 'category',
      label: 'Asset API',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/asset',
        }
      ],
    },
    {
      type: 'category',
      label: 'Products and Services API',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/product',
        }
      ],
    },
    {
      type: 'category',
      label: 'Contact API',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/contact',
        }
      ],
    },
    {
      type: 'category',
      label: 'Customer API',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/customer',
        }
      ],
    },
    {
      type: 'category',
      label: 'Project / Deal API',
      link: {
        type: 'generated-index'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/deal',
        }
      ]
    },
    {
      type: 'category',
      label: 'Activity API',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api/activity',
        }
      ],
    },
  ],

  // But you can create a sidebar manually
  // mainDocs: [
  //   'intro',
  //   'hello-world',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
};

export default sidebars;
